### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function wpsql_connect()

### ISSUE THREAD

**Issue by iamdriz** [php4dev/heroku-wordpress#22]
When using this setup I get the following error in the Heroku logs:

```
2021-03-06T18:29:27.144227+00:00 app[web.1]: [06-Mar-2021 18:29:27 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wpsql_connect() in /app/public/wp-content/pg4wp/core.php(35) : eval()'d code:1688
2021-03-06T18:29:27.144236+00:00 app[web.1]: Stack trace:
2021-03-06T18:29:27.144399+00:00 app[web.1]: #0 /app/public/wp-content/pg4wp/core.php(35) : eval()'d code(632): wpdb2->db_connect()
2021-03-06T18:29:27.144524+00:00 app[web.1]: #1 /app/public/wp-content/pg4wp/core.php(39): wpdb2->__construct()
2021-03-06T18:29:27.144654+00:00 app[web.1]: #2 /app/public/wp-content/db.php(35): require_once('...')
2021-03-06T18:29:27.144796+00:00 app[web.1]: #3 /app/public/wp-includes/load.php(515): require_once('...')
2021-03-06T18:29:27.144903+00:00 app[web.1]: #4 /app/public/wp-settings.php(124): require_wp_db()
2021-03-06T18:29:27.145012+00:00 app[web.1]: #5 /app/public/wp-config.php(130): require_once('...')
2021-03-06T18:29:27.145120+00:00 app[web.1]: #6 /app/public/wp-load.php(42): require_once('...')
2021-03-06T18:29:27.145239+00:00 app[web.1]: #7 /app/public/wp-blog-header.php(13): require_once('...')
2021-03-06T18:29:27.145397+00:00 app[web.1]: #8 /app/public/index.php(17): require('...')
2021-03-06T18:29:27.145398+00:00 app[web.1]: #9 {main}
2021-03-06T18:29:27.145530+00:00 app[web.1]:   thrown in /app/public/wp-content/pg4wp/core.php(35) : eval()'d code on line 1688
```

This is with WordPress 5.6.3 and PHP 7.3.0.

Any ideas why this is happening? Or is this plugin no longer supported for WordPress? Thanks.

**Comment by javadev** [comment]
Thank you for the issue. I will check start on new application.

**Comment by javadev** [comment]
I tested on heroku. It works.

![Screenshot_984](https://user-images.githubusercontent.com/348496/117952029-70091900-b31d-11eb-90ac-41fc27928e82.png)
